export type AutomationPlatform = 'wirenboard' | 'homeassistant';

export interface AutomationDeviceMapping {
  id: string;
  deviceId: string;
  deviceType: string;
  deviceName: string;
  roomName?: string;
  channel?: number;
  mappedType: 'switch' | 'light' | 'dimmer' | 'rgb' | 'sensor' | 'relay' | 'thermostat';
  address?: string; // modbus address for WB
}

export interface AutomationConfigData {
  id: string;
  projectId: string;
  platform: AutomationPlatform;
  name: string;
  devices: AutomationDeviceMapping[];
  script: string;
  createdAt?: string;
  updatedAt?: string;
}

const WB_TEMPLATES: Record<string, string> = {
  relay: 'WB-MR6C',
  dimmer: 'WB-MRGBW-D',
  rgb: 'WB-MRGBW-D',
  sensor: 'WB-MSW',
  switch: 'WB-MR6C',
  light: 'WB-MRGBW-D',
  thermostat: 'WB-MSW',
};

function wbDeviceTemplate(device: AutomationDeviceMapping): string {
  const template = WB_TEMPLATES[device.mappedType] ?? 'WB-MR6C';
  const name = device.deviceName || `device_${device.deviceId.slice(0, 6)}`;
  const channel = device.channel ?? 1;
  return `
// ${name} (${device.mappedType})
defineVirtualDevice('${name}', {
  title: '${name}',
  cells: {
    ${device.mappedType === 'switch' || device.mappedType === 'relay' || device.mappedType === 'light' ? `'K${channel}': { type: 'switch', value: false },` : ''}
    ${device.mappedType === 'dimmer' || device.mappedType === 'rgb' ? `'Dim${channel}': { type: 'range', value: 0, max: 255 },` : ''}
    ${device.mappedType === 'sensor' || device.mappedType === 'thermostat' ? `'Temperature': { type: 'temperature', value: 0 },` : ''}
  },
});
`.trim();
}

export function generateWirenboardConfig(mappings: AutomationDeviceMapping[]): string {
  const header = `// Generated by InvoltCAD for Wirenboard
// Platform: wirenboard
// Devices: ${mappings.length}
`;
  const body = mappings.map(wbDeviceTemplate).join('\n\n');
  return header + '\n' + body;
}

function haEntityId(device: AutomationDeviceMapping): string {
  const type = device.mappedType === 'switch' || device.mappedType === 'relay' ? 'switch'
    : device.mappedType === 'light' || device.mappedType === 'dimmer' || device.mappedType === 'rgb' ? 'light'
    : device.mappedType === 'sensor' || device.mappedType === 'thermostat' ? 'sensor'
    : 'binary_sensor';
  const name = (device.deviceName || `device_${device.deviceId.slice(0, 6)}`).toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
  return `${type}.${name}`;
}

function haYamlEntity(device: AutomationDeviceMapping): string {
  const entityId = haEntityId(device);
  const name = device.deviceName || entityId;
  const room = device.roomName ? `  room: "${device.roomName}"\n` : '';

  if (device.mappedType === 'switch' || device.mappedType === 'relay') {
    return `- platform: mqtt\n  name: "${name}"\n  command_topic: "involtcad/${device.deviceId}/set"\n  state_topic: "involtcad/${device.deviceId}/state"\n  payload_on: "ON"\n  payload_off: "OFF"\n  state_on: "ON"\n  state_off: "OFF"\n${room}`;
  }
  if (device.mappedType === 'light' || device.mappedType === 'dimmer' || device.mappedType === 'rgb') {
    return `- platform: mqtt\n  name: "${name}"\n  schema: json\n  command_topic: "involtcad/${device.deviceId}/set"\n  state_topic: "involtcad/${device.deviceId}/state"\n  brightness: true\n${room}`;
  }
  if (device.mappedType === 'sensor' || device.mappedType === 'thermostat') {
    return `- platform: mqtt\n  name: "${name}"\n  state_topic: "involtcad/${device.deviceId}/state"\n  unit_of_measurement: "°C"\n  device_class: temperature\n${room}`;
  }
  return `- platform: mqtt\n  name: "${name}"\n  state_topic: "involtcad/${device.deviceId}/state"\n${room}`;
}

export function generateHomeAssistantConfig(mappings: AutomationDeviceMapping[]): string {
  const header = `# Generated by InvoltCAD for Home Assistant
# Platform: homeassistant
# Devices: ${mappings.length}
`;
  const switches = mappings.filter((d) => d.mappedType === 'switch' || d.mappedType === 'relay').map(haYamlEntity).join('\n');
  const lights = mappings.filter((d) => d.mappedType === 'light' || d.mappedType === 'dimmer' || d.mappedType === 'rgb').map(haYamlEntity).join('\n');
  const sensors = mappings.filter((d) => d.mappedType === 'sensor' || d.mappedType === 'thermostat').map(haYamlEntity).join('\n');
  const others = mappings.filter((d) => !['switch', 'relay', 'light', 'dimmer', 'rgb', 'sensor', 'thermostat'].includes(d.mappedType)).map(haYamlEntity).join('\n');

  let yaml = header;
  if (switches) yaml += '\nswitch:\n' + switches;
  if (lights) yaml += '\nlight:\n' + lights;
  if (sensors) yaml += '\nsensor:\n' + sensors;
  if (others) yaml += '\nbinary_sensor:\n' + others;
  return yaml;
}

export function buildAutomationMappingsFromPlan(
  devices: Array<{ id: string; type: string; name: string; roomName?: string }>,
  circuits?: Array<{ id: string; name: string; type: string }>,
): AutomationDeviceMapping[] {
  const mappings: AutomationDeviceMapping[] = [];
  let channel = 1;

  for (const device of devices) {
    let mappedType: AutomationDeviceMapping['mappedType'] = 'switch';
    if (device.type === 'light' || device.type === 'dimmer' || device.type === 'rgb') mappedType = 'light';
    else if (device.type === 'socket' || device.type === 'outlet') mappedType = 'switch';
    else if (device.type === 'switch') mappedType = 'switch';
    else if (device.type === 'heating' || device.type === 'thermostat') mappedType = 'thermostat';
    else if (device.type === 'sensor' || device.type === 'lowcurrent') mappedType = 'sensor';
    else mappedType = 'switch';

    mappings.push({
      id: `map-${device.id}`,
      deviceId: device.id,
      deviceType: device.type,
      deviceName: device.name,
      roomName: device.roomName,
      channel,
      mappedType,
      address: `0x${(10 + channel).toString(16).padStart(2, '0')}`,
    });
    channel++;
  }

  for (const circuit of circuits ?? []) {
    mappings.push({
      id: `circuit-${circuit.id}`,
      deviceId: circuit.id,
      deviceType: 'circuit',
      deviceName: circuit.name,
      mappedType: 'switch',
      channel,
      address: `0x${(10 + channel).toString(16).padStart(2, '0')}`,
    });
    channel++;
  }

  return mappings;
}

export function generateAutomationConfig(platform: AutomationPlatform, mappings: AutomationDeviceMapping[]): string {
  if (platform === 'wirenboard') return generateWirenboardConfig(mappings);
  return generateHomeAssistantConfig(mappings);
}
