import { describe, it, expect } from 'vitest';
import { generateAutomationConfig, generateWirenboardConfig, generateHomeAssistantConfig, buildAutomationMappingsFromPlan, AutomationDeviceMapping } from './AutomationEngine';

describe('AutomationEngine', () => {
  const mappings: AutomationDeviceMapping[] = [
    { id: 'm1', deviceId: 'd1', deviceType: 'socket', deviceName: 'Розетка кухня', mappedType: 'switch', channel: 1 },
    { id: 'm2', deviceId: 'd2', deviceType: 'light', deviceName: 'Свет спальня', mappedType: 'dimmer', channel: 2 },
  ];

  it('generates Wirenboard config', () => {
    const config = generateWirenboardConfig(mappings);
    expect(config).toContain('// Generated by InvoltCAD for Wirenboard');
    expect(config).toContain("defineVirtualDevice('Розетка кухня'");
    expect(config).toContain("type: 'switch'");
    expect(config).toContain('Dim2');
  });

  it('generates Home Assistant config', () => {
    const config = generateHomeAssistantConfig(mappings);
    expect(config).toContain('# Generated by InvoltCAD for Home Assistant');
    expect(config).toContain('switch:');
    expect(config).toContain('light:');
    expect(config).toContain('command_topic:');
  });

  it('selects platform generator', () => {
    expect(generateAutomationConfig('wirenboard', mappings)).toContain('Wirenboard');
    expect(generateAutomationConfig('homeassistant', mappings)).toContain('Home Assistant');
  });

  it('builds mappings from plan devices', () => {
    const planDevices = [
      { id: 'd1', type: 'socket', name: 'Розетка' },
      { id: 'd2', type: 'light', name: 'Свет' },
      { id: 'd3', type: 'thermostat', name: 'Тёплый пол' },
    ];
    const result = buildAutomationMappingsFromPlan(planDevices);
    expect(result).toHaveLength(3);
    expect(result[0].mappedType).toBe('switch');
    expect(result[1].mappedType).toBe('light');
    expect(result[2].mappedType).toBe('thermostat');
    expect(result[0].channel).toBe(1);
  });
});
